config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'calendars#top'
  resources :calendars, only: :index 
  resources :schedules
  resources :todos
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/color.rb
class Color < ActiveHash::Base
  self.data = [
    { id: 1, name: '選択してください' },
    { id: 2, name: 'ブルー' },
    { id: 3, name: 'グリーン' },
    { id: 4, name: 'ブラウン' },
    { id: 5, name: 'オレンジ' },
    { id: 6, name: 'パープル' },
    { id: 7, name: 'ピンク' }
  ]
end

app/models/countdown.rb
class Countdown < ActiveHash::Base
  self.data = [
   { id: 1, name: '選択してください' },
   { id: 2, name: 'カウントダウンしない' },
   { id: 3, name: 'カウントダウンする' }
 ]
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :countdown
  belongs_to_active_hash :color
  
  belongs_to :user
  
  validates :name, :start_time, :countdown, :color, presence: true
  validates :countdown_id, :color_id, numericality: { other_than: 1, message: 'を選択してください' } 
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :name, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :name, presence: true

  has_many :schedules
  has_many :todos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top]
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth

  def after_sign_in_path_for(resource)
    calendars_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"] 
    end
  end
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController

  def top
  end
  
  def index
    @schedule = Schedule.where(user_id: current_user.id).all
    @todos = Todo.where(user_id: current_user.id).all
    @todo = Todo.new
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]
  def show
  end

  def new
    @schedule = Schedule.new
  end

  def create
    @schedule = Schedule.new(schedule_params)
    if @schedule.valid?
      @schedule.save
      redirect_to calendars_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @schedule.update(schedule_params)
      redirect_to schedule_path
    else
      render 'edit'
    end
  end

  def destroy
    if @schedule.destroy
      redirect_to calendars_path
    else
      render 'show'
    end
  end
  
  private

  def schedule_params
    params.require(:schedule).permit(:name, :start_time, :end_time, :countdown_id, :color_id).merge(user_id: current_user.id)
  end

  def set_schedule
    @schedule = Schedule.find(params[:id])
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      redirect_to calendars_path
    end
  end

  def destroy
    @todo = Todo.find(params[:id])
    if @todo.destroy
      redirect_to calendars_path
    end
  end

  private
  def todo_params
    params.require(:todo).permit(:name).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/calendars/index.html.erb
<div class="wrapper">
  <div class="main">
    <%= month_calendar events: @schedule do |date, schedule| %>
      <%= date.day %>
      
        <% schedule.each do |schedule| %>
          <% if schedule.color_id == 2 %>
            <div>
              <%= link_to schedule.name, schedule_path(schedule.id), style: "color: deepskyblue"%>
            </div>
          <% elsif schedule.color_id == 3 %>
            <div>
              <%= link_to schedule.name, schedule_path(schedule.id), style: "color: mediumseagreen"%>
            </div>
          <% elsif schedule.color_id == 4 %>
            <div>
              <%= link_to schedule.name, schedule_path(schedule.id), style: "color: saddlebrown"%>
            </div>
          <% elsif schedule.color_id == 5 %>
            <div>
              <%= link_to schedule.name, schedule_path(schedule.id), style: "color: darkorange"%>
            </div>
          <% elsif schedule.color_id == 6 %>
            <div>
              <%= link_to schedule.name, schedule_path(schedule.id), style: "color: blueviolet"%>
            </div>
          <% else schedule.color_id == 7 %>
            <div>
              <%= link_to schedule.name, schedule_path(schedule.id), style: "color: violet"%>
            </div>
          <% end %>
        <% end %>
    <% end %>
    <%= link_to "予定作成", new_schedule_path, class: 'create_btn'%>
  </div>

  <div class="side_bar">
    <div class="countdown">
      <h2>Countdown</h2>
      <% @schedule.each do |schedule|%>
        <% if schedule.countdown_id == 3 %>
          <% today = Date.today.jd %>
          <% limit = schedule.start_time.to_date.jd %>
          <% remain = limit - today %>
          <% if remain >= 4 %>
            <div class="counts">
            <%= "#{schedule.name}まであと#{remain}日" %>
            </div>
          <% elsif remain >= 0 && remain <= 3 %>
            <div class="counts_color">
            <%= "#{schedule.name}まであと#{remain}日" %>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
      
    <div class="todo">
      <h2>ToDo リスト</h2>
      <% @todos.each do |todo| %>
        <div class="tasks">
        <input type="checkbox"><%= todo.name %>
        <%= link_to image_tag("trash.png", :size =>'15x15'),todo_path(todo.id), method: :delete %>
        </div>
      <% end %>
      <%= form_with model: @todo, local: true  do |f| %>
        <div class="send">
        <%= f.text_field :name %>
        <%= f.submit %>
        </div>
      <% end %>
    </div>

    <div class="account">
      <%= link_to "アカウントを削除する", user_registration_path, method: :delete, class: "delete"%>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "logout" %>
    </div>
  </div>
</div>

app/views/calendars/top.html.erb
<div class="cover">
  <div class="title">
    <h1>ProductiveDays</h1>
    <p>
    せっかくの休日なのに、１日中寝て過ごしてしまった…<br>
    試験の前日、もっと勉強しておけば良かった…<br>
    と後悔したことはありませんか？<br>
    <br>
    このアプリは充実した日々を過ごすのに<br>
    ぴったりの予定管理ツールです。<br>
    今日という日をProductiveな１日にしませんか？
    </p>
    <%= link_to "いますぐ無料で始める", new_user_registration_path, class: "sign-up"%>
    <%= link_to "アカウントをお持ちの方はこちら", new_user_session_path, class: "sign-in"%>
  </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
 <ul>
   <% model.errors.full_messages.each do |message| %>
   <li class='error-message'><%= message %></li>
   <% end %>
 </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductiveDays</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/schedules/edit.html.erb
<h1 class="schedule_form">予定編集</h1>
<div class="schedule">
  <%= form_with model: @schedule, url:schedule_path, local: true do |f| %>
    <div class="schedule-box">
      <div class="create">
        <label class="control-label" for="">予定</label>
        <%= f.text_field :name, class:"event_name" %>
      </div>
      <div class="create">
        <label class="control-label" for="">Start</label>
        <%= f.datetime_select :start_time, class:"time" %>
      </div>
      <div class="create">
        <label class="control-label" for="">End</label>
        <%= f.datetime_select :end_time, class:"time" %>
      </div>
      <div class="create">
        <label class="control-label" for="">テーマカラー</label>
        <%= f.collection_select(:color_id, Color.all, :id, :name, {}, {class:"color-select"}) %>
      </div>
      <div class="create">
        <label class="control-label" for="">カウントダウン</label>
        <%= f.collection_select(:countdown_id, Countdown.all, :id, :name, {}, {class:"countdown-select"}) %>
      </div>
      <div class="create">
        <%= f.submit "OK" ,class:"btn" %>
      </div>
    </div>
  <% end %>
</div>

app/views/schedules/new.html.erb
<h1 class="schedule_form">予定作成</h1>
<div class="schedule">
  <%= form_with model: @schedule, url:schedules_path, local: true do |f| %>
    <div class="error-messages">
    <%= render 'layouts/error_messages', model: f.object %>
    </div>
    <div class="schedule-box">
      <div class="create">
        <label class="control-label" for="">予定</label>
        <%= f.text_field :name, class:"event_name" %>
      </div>
      <div class="create">
        <label class="control-label" for="">Start</label>
        <%= f.datetime_select :start_time, class:"time" %>
      </div>
      <div class="create">
        <label class="control-label" for="">End</label>
        <%= f.datetime_select :end_time, class:"time" %>
      </div>
      <div class="create">
        <label class="control-label" for="">テーマカラー</label>
        <%= f.collection_select(:color_id, Color.all, :id, :name, {}, {class:"color-select"}) %>
      </div>
      <div class="create">
        <label class="control-label" for="">カウントダウン</label>
        <%= f.collection_select(:countdown_id, Countdown.all, :id, :name, {}, {class:"countdown-select"}) %>
      </div>
      <div class="create">
        <%= f.submit "OK" ,class:"btn" %>
      </div>
    </div>
  <% end %>
</div>

<%= link_to "戻る", calendars_path, class: 'back_btn' %>

app/views/schedules/show.html.erb
<p>
  <strong><%= @schedule.start_time.strftime("%Y-%m-%d %H:%M") %> 〜 <%= @schedule.end_time.strftime("%Y-%m-%d %H:%M") %></strong>
</p>

<p>
  <strong><%= @schedule.name %></strong>
</p>


<%= link_to "編集", edit_schedule_path %>
<%= link_to "削除", schedule_path, method: :delete %>
<%= link_to "戻る", calendars_path%>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '<<'), calendar.url_for_previous_view, class: "prev" %>
    <span class="calendar-title"><%= start_date.year %> <%= t('date.month_names')[start_date.month] %></span>
    <%= link_to t('simple_calendar.next', default: '>>'), calendar.url_for_next_view, class: "next"%>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th class="day_name"><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>